# Generated by Django 3.1.2 on 2021-03-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=30)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetail',
            fields=[
                ('Employee_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('date_of_birth', models.DateField(blank=True)),
                ('CID', models.CharField(blank=True, max_length=11, unique=True)),
                ('category', models.CharField(blank=True, choices=[('Administration', 'Administration'), ('Teaching Staff', 'Teaching Staff'), ('Non Teaching Staff', 'Non Teaching Staff'), ('Supporting Staff', 'Supporting Staff')], max_length=30)),
                ('position_title', models.CharField(blank=True, max_length=50)),
                ('position_level', models.CharField(blank=True, max_length=10)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('appointment_date', models.DateField(blank=True)),
                ('joining_date_of_present_school', models.DateField(blank=True)),
                ('transfered_from', models.CharField(blank=True, max_length=50)),
                ('Employment_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Contract', 'Contract')], max_length=30)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('qualification', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, default='/static/images/user.jpg', null=True, upload_to='images/staff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('student_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('standard', models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=30)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=30)),
                ('date_of_birth', models.DateField(blank=True)),
                ('admission_no', models.BigIntegerField(blank=True)),
                ('date_of_admission', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('CID', models.CharField(blank=True, max_length=11, unique=True)),
                ('previous_school', models.CharField(blank=True, max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=8)),
                ('permanent_address', models.TextField(blank=True)),
                ('BoarderOrDayscholar', models.CharField(blank=True, choices=[('Boarder', 'Boarder'), ('Dayscholar', 'Dayscholar')], max_length=30)),
                ('RegularOrRepeater', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Repeater', 'Repeater')], max_length=30)),
                ('profile_pic', models.ImageField(blank=True, default='/static/images/user.jpg', null=True, upload_to='images/students')),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('mother_name', models.CharField(blank=True, max_length=50)),
                ('fathers_occupation', models.CharField(blank=True, max_length=50)),
                ('mothers_occupation', models.CharField(blank=True, max_length=50)),
                ('parents_mobile_number', models.CharField(blank=True, max_length=8)),
                ('class_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management_system_app.classteacher')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management_system_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Violation_detail', models.TextField()),
                ('Violation_date', models.DateField()),
                ('Warning_decision', models.TextField()),
                ('Approved_by', models.CharField(max_length=50)),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management_system_app.studentdetail')),
            ],
        ),
        migrations.AddField(
            model_name='classteacher',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_system_app.course'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_system_app.staffdetail'),
        ),
        migrations.CreateModel(
            name='CharacterCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Special_Recognition', 'Special_Recognition'), ('Volunteerism', 'Volunteerism'), ('Academic', 'Academic'), ('Games and Sports', 'Games and Sports'), ('Literary', 'Literary'), ('Cultural', 'Cultural')], max_length=30)),
                ('Description', models.TextField()),
                ('Awarded_on', models.DateField()),
                ('Awarded_by', models.CharField(max_length=100)),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management_system_app.studentdetail')),
            ],
        ),
    ]
