# Generated by Django 3.1.2 on 2021-04-01 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='proctor_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management_system_app.staffdetail'),
        ),
    ]
